import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

const PrivacyPolicy = () => {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <Navbar />
            <main className="pt-32 pb-20 px-6 max-w-4xl mx-auto font-body">
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.5 }}
                >
                    <h1 className="font-heading text-4xl md:text-5xl font-bold mb-4 text-white">Privacy Policy</h1>
                    <p className="text-muted-foreground mb-10 text-sm">Last updated: February 25, 2026</p>

                    <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground leading-relaxed text-sm md:text-base">
                        <section>
                            <p>
                                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                            </p>
                            <p className="mt-4">
                                We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Interpretation and Definitions</h2>
                            <h3 className="text-xl font-bold text-white mb-2 font-heading font-heading">Interpretation</h3>
                            <p>
                                The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                            </p>

                            <h3 className="text-xl font-bold text-white mb-2 mt-6 font-heading">Definitions</h3>
                            <p className="mb-4">For the purposes of this Privacy Policy:</p>
                            <ul className="list-disc pl-6 space-y-4">
                                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Learnovac.</li>
                                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                                <li><strong>Country</strong> refers to: California, United States.</li>
                                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                                <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
                                <li><strong>Service</strong> refers to the Website.</li>
                                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                                <li><strong>Website</strong> refers to learnovac, accessible from <a href="https://learnovac.com" className="text-primary hover:underline">https://learnovac.com</a>.</li>
                                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Collecting and Using Your Personal Data</h2>
                            <h3 className="text-xl font-bold text-white mb-2 font-heading">Types of Data Collected</h3>

                            <h4 className="text-lg font-bold text-white mb-2 mt-4 font-heading">Personal Data</h4>
                            <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                            <ul className="list-disc pl-6 space-y-2 mb-6">
                                <li>Email address</li>
                                <li>First name and last name</li>
                                <li>Phone number</li>
                                <li>Address, State, Province, ZIP/Postal code, City</li>
                            </ul>

                            <h4 className="text-lg font-bold text-white mb-2 mt-4 font-heading">Usage Data</h4>
                            <p>Usage Data is collected automatically when using the Service.</p>
                            <p className="mt-4">
                                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-xl font-bold text-white mb-4 font-heading">Tracking Technologies and Cookies</h3>
                            <p>
                                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                            </p>
                            <ul className="list-disc pl-6 space-y-4 mt-4">
                                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Retention of Your Personal Data</h2>
                            <p>
                                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                            </p>
                            <p className="mt-4">
                                Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Security of Your Personal Data</h2>
                            <p>
                                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Detailed Information on the Processing of Your Personal Data</h2>
                            <p className="mb-4">The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>

                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-xl font-bold text-white mb-2 font-heading">Mouseflow</h3>
                                    <p>Mouseflow is a session replay and heatmap tool that shows how visitors click, move, scroll, browse, and pay attention on websites. The service is operated by ApS.</p>
                                    <p className="mt-2 text-sm">Privacy Policy: <a href="https://mouseflow.com/privacy/" className="text-primary hover:underline">https://mouseflow.com/privacy/</a></p>
                                </div>
                                <div>
                                    <h3 className="text-xl font-bold text-white mb-2 font-heading">FreshDesk</h3>
                                    <p>FreshDesk is a customer support software. The service is operated by Freshworks, Inc.</p>
                                    <p className="mt-2 text-sm">Privacy Policy: <a href="https://www.freshworks.com/privacy/" className="text-primary hover:underline">https://www.freshworks.com/privacy/</a></p>
                                </div>
                                <div>
                                    <h3 className="text-xl font-bold text-white mb-2 font-heading">Google Places</h3>
                                    <p>Google Places is a service that returns information about places using HTTP requests. It is operated by Google.</p>
                                    <p className="mt-2 text-sm">Privacy Policy: <a href="https://www.google.com/intl/en/policies/privacy/" className="text-primary hover:underline">https://www.google.com/intl/en/policies/privacy/</a></p>
                                </div>
                            </div>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Children's Privacy</h2>
                            <p>
                                Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4 font-heading">Contact Us</h2>
                            <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li><strong>By email:</strong> support@learnovac.com</li>
                                <li><strong>By visiting:</strong> <a href="https://learnovac.com" className="text-primary hover:underline">https://learnovac.com</a></li>
                                <li><strong>By phone:</strong> +1 323-284-8812</li>
                                <li><strong>By mail:</strong> 3300 Sunset Blvd, Los Angeles, CA 90026, United States</li>
                            </ul>
                        </section>
                    </div>
                </motion.div>
            </main>
            <Footer />
        </div>
    );
};

export default PrivacyPolicy;
